export const TextTypes = {
  PAGE_HEADING: "PAGE_HEADING",
  PAGE_SUB_HEADING: "PAGE_SUB_HEADING",
  SECTION_HEADING: "SECTION_HEADING",
  SECTION_SUB_HEADING: "SECTION_SUB_HEADING",
  CARD_HEADING: "CARD_HEADING",
  CARD_SUBHEADING: "CARD_SUBHEADING",
  FOOTER_HEADING: "FOOTER_HEADING",
};
